---
title: "Partners"
description: "ReDiLEEP consortium partners."
---

::: {.page-heading}
# Partners

ReDiLEEP is a consortium of beneficiaries, associated partners, supervisors, and sector collaborators spanning Europe and wider international research networks.
:::

::: {.section .partner-list}
::: {.partner-entry}
### Linköping University

**LiU | Beneficiary | SE**  
Department of Physics Chemistry and Biology (IFM)  
Scientist in charge: Anna Eklöf.  
Coordinator; beneficiary; leads WP5 and WP6; hosts DC1 and DC2
:::

::: {.partner-entry}
### University of Oldenburg

**UOL | Beneficiary | DE**  
Institute for Chemistry and Biology of Marine Environments (ICBM)  
Scientist in charge: Helmut Hillebrand.  
Beneficiary; leads WP3; hosts DC3
:::

::: {.partner-entry}
### University of Namur

**UNamur | Beneficiary | BE**  
Institute of complex systems (naXys); Institute of Life Earth and the Environment (ILEE)  
Scientist in charge: Frederik De Laender.  
Beneficiary; leads WP2; hosts DC6 and DC7
:::

::: {.partner-entry}
### Cardiff University

**CarU | Beneficiary | UK**  
School of Biosciences  
Scientist in charge: Fredric Windsor.  
Beneficiary; leads WP1; hosts DC4 and DC5
:::

::: {.partner-entry}
### University of Helsinki

**UH | Beneficiary | FI**  
Faculty of Biological and Environmental Sciences  
Scientist in charge: Elina Kaarlejarvi.  
Beneficiary; leads WP4; hosts DC9
:::

::: {.partner-entry}
### Agencia Estatal Consejo Superior de Investigaciones Científicas

**CSIC | Beneficiary | ES**  
Centro de Investigaciones sobre Desertificación  
Scientist in charge: Francesco de Bello.  
Beneficiary; hosts DC8 with Universitat de València as PhD-awarding organisation
:::

::: {.partner-entry}
### Swansea University

**SwanU | Beneficiary | UK**  
Department of Biosciences  
Scientist in charge: Mike Fowler.  
Beneficiary; hosts DC10
:::

::: {.partner-entry}
### University of Zurich

**UZH | Beneficiary | CH**  
Department of Evolutionary Biology and Environmental Studies; Department of Geography  
Scientist in charge: Owen Petchey.  
Beneficiary; hosts DC11 and DC12
:::

::: {.partner-entry}
### Monash University

**Monash | Associated partner | AU**  
School of Biological Sciences  
Scientist in charge: Giulia Ghedini.  
Recruitment and supervision of students; secondments; provision of training
:::

::: {.partner-entry}
### Okinawa Institute of Science and Technology Graduate University

**OIST | Associated partner | JP**  
Integrative Community Ecology Unit  
Scientist in charge: Samuel RP-J Ross.  
Co-supervision of students; secondments; provision of training
:::

::: {.partner-entry}
### Lutra Interactive

**Lutra | Associated partner | SE**  
N/A  
Scientist in charge: Anna Eklof.  
Provision of training
:::

::: {.partner-entry}
### Zulu Ecosystems

**Zulu | Associated partner | UK**  
N/A  
Scientist in charge: Claire Burke.  
Co-supervision of students; secondments; provision of training
:::

::: {.partner-entry}
### Earth Species Project

**ESP | Associated partner | US**  
N/A  
Scientist in charge: Sara Keen.  
Co-supervision of students; secondments; provision of training
:::

::: {.partner-entry}
### Advanced Invasives

**AdIn | Associated partner | UK**  
N/A  
Scientist in charge: Daniel Jones.  
Co-supervision of students; secondments; provision of training
:::

::: {.partner-entry}
### Generalitat Valenciana / CIEF

**GENVAL / CIEF | Associated partner | ES**  
CIEF  
Scientist in charge: Guillermo Casanova.  
Use of seed bank growth chambers and training in seed use and manipulation
:::

::: {.partner-entry}
### Trinity College Dublin

**TCD | Associated partner | IE**  
Department of Zoology  
Scientist in charge: Ian Donohue.  
Secondment host
:::

::: {.partner-entry}
### Swedish Environmental Protection Agency

**SEPA | Associated partner | SE**  
Nature Analysis Unit  
Scientist in charge: Thomas Lyrholm.  
Training and secondment host
:::

::: {.partner-entry}
### ThinkNature

**TN | Associated partner | JP**  
N/A  
Scientist in charge: Buntarou Kusumoto.  
Secondments and provision of training
:::

::: {.partner-entry}
### Welsh Government

**WGov | Associated partner | UK**  
Biodiversity Targets Team  
Scientist in charge: Kathryn Mullins.  
Secondments
:::

::: {.partner-entry}
### Universitat de València

**UVEG | Associated partner linked to beneficiary | ES**  
Programa de Doctorat en Biodiversitat i Biologia Evolutiva  
Scientist in charge: to be confirmed.  
PhD-awarding organisation for CSIC
:::

:::


